// .claude/Salah Bahzad Teacher Portal/Combobox.jsx
/**
 * Combobox — dropdown with autocomplete (typeahead filtering)
 *
 * A text input that filters a list of options as you type. Keyboard
 * navigable, clears with ×, and falls back to a "no matches" row.
 *
 * @startingPoint section="Forms" subtitle="Autocomplete" viewport="360x140"
 */
function Combobox({ label, value, onChange, options = [], placeholder = 'Type to search…', disabled, error, required, emptyText = 'No matches' }) {
  const [open, setOpen] = React.useState(false);
  const [query, setQuery] = React.useState('');
  const [active, setActive] = React.useState(0);
  const rootRef = React.useRef(null);
  const selected = options.find((o) => o.value === value);

  // Show selected label in the field when closed; the live query while open.
  const display = open ? query : (selected ? selected.label : '');
  const filtered = React.useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!open || !q) return options;
    return options.filter((o) => o.label.toLowerCase().includes(q));
  }, [query, options, open]);

  React.useEffect(() => {
    if (!open) return;
    const onDoc = (e) => { if (rootRef.current && !rootRef.current.contains(e.target)) close(); };
    document.addEventListener('mousedown', onDoc);
    return () => document.removeEventListener('mousedown', onDoc);
  }, [open, query]);

  const close = () => { setOpen(false); setQuery(''); };
  const choose = (o) => { if (o.disabled) return; onChange?.(o.value); close(); };

  const onKey = (e) => {
    if (e.key === 'ArrowDown') { e.preventDefault(); setOpen(true); setActive((i) => Math.min(filtered.length - 1, i + 1)); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); setActive((i) => Math.max(0, i - 1)); }
    else if (e.key === 'Enter') { e.preventDefault(); if (open && filtered[active]) choose(filtered[active]); }
    else if (e.key === 'Escape') { close(); }
  };

  const borderColor = error ? 'var(--sb-danger)' : open ? 'var(--sb-primary)' : 'var(--sb-border-strong)';

  return (
    <div ref={rootRef} style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sb-space-1)', fontFamily: 'var(--sb-font-sans)', position: 'relative' }}>
      {label && (
        <label style={{ fontSize: 'var(--sb-label-lg-size)', fontWeight: 600, color: 'var(--sb-text)' }}>
          {label}{required && <span style={{ color: 'var(--sb-danger)' }}> *</span>}
        </label>
      )}
      <div style={{
        display: 'flex', alignItems: 'center', gap: 'var(--sb-space-2)', height: 40, padding: '0 12px',
        border: `1px solid ${borderColor}`, borderRadius: 'var(--sb-radius-md)',
        background: disabled ? 'var(--sb-surface-sunken)' : 'var(--sb-surface)',
        boxShadow: open ? 'var(--sb-shadow-focus)' : 'none', opacity: disabled ? 0.55 : 1,
        transition: 'border-color var(--sb-timing-fast), box-shadow var(--sb-timing-fast)',
      }}>
        <span aria-hidden style={{ color: 'var(--sb-text-subtle)', fontSize: 15, lineHeight: 1 }}>⌕</span>
        <input
          type="text" value={display} placeholder={placeholder} disabled={disabled}
          onChange={(e) => { setQuery(e.target.value); setOpen(true); setActive(0); }}
          onFocus={() => setOpen(true)} onKeyDown={onKey} role="combobox" aria-expanded={open} aria-autocomplete="list"
          style={{
            flex: 1, minWidth: 0, border: 'none', outline: 'none', background: 'transparent',
            fontFamily: 'inherit', fontSize: 'var(--sb-body-md-size)', color: 'var(--sb-text)',
            cursor: disabled ? 'not-allowed' : 'text',
          }}
        />
        {selected && !disabled && (
          <button type="button" aria-label="Clear" onMouseDown={(e) => e.preventDefault()} onClick={() => { onChange?.(''); close(); }}
            style={{ border: 'none', background: 'var(--sb-neutral-100)', color: 'var(--sb-text-muted)', width: 20, height: 20, borderRadius: '50%', cursor: 'pointer', fontSize: 13, lineHeight: 1, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>×</button>
        )}
        <span aria-hidden style={{ color: 'var(--sb-text-muted)', fontSize: 12, transform: open ? 'rotate(180deg)' : 'none', transition: 'transform var(--sb-timing-fast)' }}>▾</span>
      </div>

      {open && (
        <ul role="listbox" style={{
          position: 'absolute', top: 'calc(100% + 6px)', left: 0, right: 0, zIndex: 50, margin: 0,
          listStyle: 'none', padding: 'var(--sb-space-1)', maxHeight: 240, overflowY: 'auto',
          background: 'var(--sb-surface)', border: '1px solid var(--sb-border)',
          borderRadius: 'var(--sb-radius-md)', boxShadow: 'var(--sb-shadow-lg)',
        }}>
          {filtered.length === 0 && (
            <li style={{ padding: '10px', fontSize: 'var(--sb-body-md-size)', color: 'var(--sb-text-subtle)', textAlign: 'center' }}>{emptyText}</li>
          )}
          {filtered.map((o, i) => {
            const isSel = o.value === value, isAct = i === active;
            return (
              <li
                key={o.value} role="option" aria-selected={isSel}
                onMouseEnter={() => setActive(i)} onMouseDown={(e) => e.preventDefault()} onClick={() => choose(o)}
                style={{
                  display: 'flex', alignItems: 'center', gap: 'var(--sb-space-2)', padding: '8px 10px',
                  borderRadius: 'var(--sb-radius-sm)', cursor: o.disabled ? 'not-allowed' : 'pointer',
                  background: isAct && !o.disabled ? 'var(--sb-primary-50)' : 'transparent',
                  color: o.disabled ? 'var(--sb-text-subtle)' : 'var(--sb-text)', opacity: o.disabled ? 0.6 : 1,
                }}
              >
                {o.icon && <span aria-hidden style={{ fontSize: 16, lineHeight: 1, flexShrink: 0 }}>{o.icon}</span>}
                <span style={{ flex: 1, minWidth: 0 }}>
                  <span style={{ display: 'block', fontSize: 'var(--sb-body-md-size)', fontWeight: isSel ? 700 : 500, lineHeight: 1.3 }}>{o.label}</span>
                  {o.description && <span style={{ display: 'block', fontSize: 'var(--sb-body-sm-size)', color: 'var(--sb-text-muted)', lineHeight: 1.3 }}>{o.description}</span>}
                </span>
                {isSel && <span aria-hidden style={{ color: 'var(--sb-primary)', fontSize: 13, flexShrink: 0 }}>✓</span>}
              </li>
            );
          })}
        </ul>
      )}
      {error && <span style={{ fontSize: 'var(--sb-body-sm-size)', color: 'var(--sb-danger-fg)' }}>{error}</span>}
    </div>
  );
}

window.SBCombobox = Combobox;

// frontend/libs/shared/ui/src/lib/combobox/combobox.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  HostListener,
  computed,
  forwardRef,
  inject,
  input,
  output,
  signal,
} from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { SelectOption } from '../select/select.component';

/**
 * Searchable single-select (the design's `Combobox`/autocomplete): a text field that filters the
 * options as you type, with keyboard navigation, a clear (×) affordance, click-outside close, and a
 * "no matches" row. Implements ControlValueAccessor so it drops into reactive forms via
 * `formControlName` / `[formControl]`, exactly like {@link SelectComponent}. The bound value is the
 * selected option's `value` (empty string when cleared).
 */
@Component({
  selector: 'sb-combobox',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    { provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => ComboboxComponent), multi: true },
  ],
  template: `
    <div
      class="sb-combo__field"
      [class.sb-combo__field--open]="open()"
      [class.sb-combo__field--invalid]="invalid()"
      [class.sb-combo__field--disabled]="isDisabled()"
    >
      <span class="sb-combo__icon" aria-hidden="true">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor"
             stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
          <path d="M21 21l-4.35-4.35M11 19a8 8 0 1 0 0-16 8 8 0 0 0 0 16z"/>
        </svg>
      </span>
      <input
        #input
        type="text"
        class="sb-combo__input"
        role="combobox"
        autocomplete="off"
        aria-autocomplete="list"
        [id]="inputId() || null"
        [attr.aria-expanded]="open()"
        [value]="display()"
        [placeholder]="placeholder()"
        [disabled]="isDisabled()"
        (input)="onInput($event)"
        (focus)="onFocus()"
        (keydown)="onKeydown($event)"
      />
      @if (selected() && !isDisabled()) {
        <button
          type="button"
          class="sb-combo__clear"
          aria-label="Clear"
          (mousedown)="$event.preventDefault()"
          (click)="clear()"
        >×</button>
      }
      <span class="sb-combo__chevron" [class.sb-combo__chevron--open]="open()" aria-hidden="true">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor"
             stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
          <path d="M6 9l6 6 6-6"/>
        </svg>
      </span>
    </div>

    @if (open()) {
      <ul class="sb-combo__menu" role="listbox">
        @if (filtered().length === 0) {
          <li class="sb-combo__empty">{{ emptyText() }}</li>
        }
        @for (option of filtered(); track option.value; let i = $index) {
          <li
            role="option"
            class="sb-combo__option"
            [class.sb-combo__option--active]="i === active() && !option.disabled"
            [class.sb-combo__option--disabled]="option.disabled"
            [attr.aria-selected]="option.value === value()"
            (mouseenter)="active.set(i)"
            (mousedown)="$event.preventDefault()"
            (click)="choose(option)"
          >
            <span class="sb-combo__option-body">
              <span
                class="sb-combo__option-label"
                [class.sb-combo__option-label--selected]="option.value === value()"
              >{{ option.label }}</span>
              @if (option.description) {
                <span class="sb-combo__option-desc">{{ option.description }}</span>
              }
            </span>
            @if (option.value === value()) {
              <span class="sb-combo__check" aria-hidden="true">
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                     stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M20 6L9 17l-5-5"/>
                </svg>
              </span>
            }
          </li>
        }
      </ul>
    }
  `,
  styles: [`
    :host { position: relative; display: block; }

    .sb-combo__field {
      display: flex;
      align-items: center;
      gap: var(--sb-space-2);
      height: 40px;
      padding: 0 12px;
      border: 1px solid var(--sb-border-strong);
      border-radius: var(--sb-radius-md);
      background: var(--sb-surface);
      transition: border-color var(--sb-timing-fast) var(--sb-easing-standard),
                  box-shadow var(--sb-timing-fast) var(--sb-easing-standard);
    }
    .sb-combo__field--open { border-color: var(--sb-primary); box-shadow: var(--sb-shadow-focus); }
    .sb-combo__field--invalid { border-color: var(--sb-danger); }
    .sb-combo__field--disabled { background: var(--sb-surface-sunken); opacity: 0.55; }

    .sb-combo__icon { display: inline-flex; color: var(--sb-text-subtle); flex-shrink: 0; }

    .sb-combo__input {
      flex: 1;
      min-width: 0;
      border: none;
      outline: none;
      background: transparent;
      font-family: var(--sb-font-sans);
      font-size: var(--sb-body-md-size);
      color: var(--sb-text);
    }
    .sb-combo__input::placeholder { color: var(--sb-text-subtle); }
    .sb-combo__input:disabled { cursor: not-allowed; }

    .sb-combo__clear {
      flex-shrink: 0;
      width: 20px;
      height: 20px;
      border: none;
      border-radius: var(--sb-radius-circle);
      background: var(--sb-neutral-100);
      color: var(--sb-text-muted);
      cursor: pointer;
      font-size: 13px;
      line-height: 1;
      display: inline-flex;
      align-items: center;
      justify-content: center;
    }
    .sb-combo__clear:hover { color: var(--sb-text); }

    .sb-combo__chevron {
      display: inline-flex;
      flex-shrink: 0;
      color: var(--sb-text-muted);
      transition: transform var(--sb-timing-fast) var(--sb-easing-standard);
    }
    .sb-combo__chevron--open { transform: rotate(180deg); }

    .sb-combo__menu {
      position: absolute;
      top: calc(100% + 6px);
      left: 0;
      right: 0;
      z-index: var(--sb-z-dropdown);
      margin: 0;
      padding: var(--sb-space-1);
      list-style: none;
      max-height: 240px;
      overflow-y: auto;
      background: var(--sb-surface);
      border: 1px solid var(--sb-border);
      border-radius: var(--sb-radius-md);
      box-shadow: var(--sb-shadow-lg);
    }

    .sb-combo__empty { padding: 10px; text-align: center; font-size: var(--sb-body-md-size); color: var(--sb-text-subtle); }

    .sb-combo__option {
      display: flex;
      align-items: center;
      gap: var(--sb-space-2);
      padding: 8px 10px;
      border-radius: var(--sb-radius-sm);
      cursor: pointer;
      color: var(--sb-text);
    }
    .sb-combo__option--active { background: var(--sb-primary-50); }
    .sb-combo__option--disabled { color: var(--sb-text-subtle); opacity: 0.6; cursor: not-allowed; }

    .sb-combo__option-body { flex: 1; min-width: 0; }
    .sb-combo__option-label { display: block; font-size: var(--sb-body-md-size); font-weight: 400; line-height: 1.3; }
    .sb-combo__option-label--selected { font-weight: 700; }
    .sb-combo__option-desc { display: block; font-size: var(--sb-body-sm-size); color: var(--sb-text-muted); line-height: 1.3; }

    .sb-combo__check { display: inline-flex; flex-shrink: 0; color: var(--sb-primary); }
  `],
})
export class ComboboxComponent implements ControlValueAccessor {
  readonly #host = inject<ElementRef<HTMLElement>>(ElementRef);

  readonly options = input<SelectOption[]>([]);
  readonly placeholder = input('Type to search…');
  readonly emptyText = input('No matches');
  readonly invalid = input(false);
  readonly inputId = input<string>('');
  readonly valueChange = output<string>();

  protected readonly open = signal(false);
  protected readonly query = signal('');
  protected readonly value = signal<string | null>(null);
  protected readonly active = signal(0);
  protected readonly isDisabled = signal(false);

  protected readonly selected = computed(() => {
    const current = this.value();
    return this.options().find((o) => o.value === current) ?? null;
  });

  /** Show the live query while open; otherwise the selected option's label. */
  protected readonly display = computed(() =>
    this.open() ? this.query() : (this.selected()?.label ?? ''),
  );

  protected readonly filtered = computed(() => {
    const q = this.query().trim().toLowerCase();
    const all = this.options();
    if (!this.open() || !q) return all;
    return all.filter((o) => o.label.toLowerCase().includes(q));
  });

  #onChange: (value: string) => void = () => {};
  #onTouched: () => void = () => {};

  // ── ControlValueAccessor ────────────────────────────────────────
  writeValue(value: string | null): void {
    this.value.set(value ?? null);
  }
  registerOnChange(fn: (value: string) => void): void {
    this.#onChange = fn;
  }
  registerOnTouched(fn: () => void): void {
    this.#onTouched = fn;
  }
  setDisabledState(isDisabled: boolean): void {
    this.isDisabled.set(isDisabled);
  }

  // ── Interaction ─────────────────────────────────────────────────
  onFocus(): void {
    if (this.isDisabled()) return;
    this.open.set(true);
    this.active.set(0);
  }

  onInput(event: Event): void {
    this.query.set((event.target as HTMLInputElement).value);
    this.open.set(true);
    this.active.set(0);
  }

  choose(option: SelectOption): void {
    if (option.disabled) return;
    this.value.set(option.value);
    this.#onChange(option.value);
    this.valueChange.emit(option.value);
    this.#close();
  }

  clear(): void {
    this.value.set('');
    this.#onChange('');
    this.valueChange.emit('');
    this.#close();
  }

  onKeydown(event: KeyboardEvent): void {
    if (this.isDisabled()) return;
    const options = this.filtered();
    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        this.open.set(true);
        this.active.update((i) => Math.min(options.length - 1, i + 1));
        break;
      case 'ArrowUp':
        event.preventDefault();
        this.active.update((i) => Math.max(0, i - 1));
        break;
      case 'Enter':
        event.preventDefault();
        if (this.open() && options[this.active()]) this.choose(options[this.active()]);
        break;
      case 'Escape':
        if (this.open()) {
          event.preventDefault();
          this.#close();
        }
        break;
      default:
        break;
    }
  }

  #close(): void {
    if (!this.open()) {
      this.query.set('');
      return;
    }
    this.open.set(false);
    this.query.set('');
    this.#onTouched();
  }

  @HostListener('document:mousedown', ['$event'])
  onDocumentMouseDown(event: MouseEvent): void {
    if (this.open() && !this.#host.nativeElement.contains(event.target as Node)) {
      this.#close();
    }
  }
}
